// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3603863308539689785),
      name: 'ArticleEmbedding',
      lastPropertyId: const obx_int.IdUid(4, 1301557118681969866),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8950706584944597076),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4797390148039915297),
            name: 'articleId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8936684604165681960),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1301557118681969866),
            name: 'embedding',
            type: 28,
            flags: 8,
            indexId: const obx_int.IdUid(1, 1221671429398070697),
            hnswParams: obx_int.ModelHnswParams(
              dimensions: 768,
              distanceType: 2,
            ))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1304910396672708484),
      name: 'ChatMessageEntity',
      lastPropertyId: const obx_int.IdUid(6, 6566647051098884281),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7365560115810031178),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7153067752905067312),
            name: 'sessionId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4693462021181268018),
            name: 'articleId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8042531193425024930),
            name: 'role',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5647064765016901766),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6566647051098884281),
            name: 'createdAt',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 1304910396672708484),
      lastIndexId: const obx_int.IdUid(1, 1221671429398070697),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ArticleEmbedding: obx_int.EntityDefinition<ArticleEmbedding>(
        model: _entities[0],
        toOneRelations: (ArticleEmbedding object) => [],
        toManyRelations: (ArticleEmbedding object) => {},
        getId: (ArticleEmbedding object) => object.id,
        setId: (ArticleEmbedding object, int id) {
          object.id = id;
        },
        objectToFB: (ArticleEmbedding object, fb.Builder fbb) {
          final articleIdOffset = fbb.writeString(object.articleId);
          final contentOffset = fbb.writeString(object.content);
          final embeddingOffset = object.embedding == null
              ? null
              : fbb.writeListFloat32(object.embedding!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, articleIdOffset);
          fbb.addOffset(2, contentOffset);
          fbb.addOffset(3, embeddingOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final articleIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final embeddingParam =
              const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final object = ArticleEmbedding(
              id: idParam,
              articleId: articleIdParam,
              content: contentParam,
              embedding: embeddingParam);

          return object;
        }),
    ChatMessageEntity: obx_int.EntityDefinition<ChatMessageEntity>(
        model: _entities[1],
        toOneRelations: (ChatMessageEntity object) => [],
        toManyRelations: (ChatMessageEntity object) => {},
        getId: (ChatMessageEntity object) => object.id,
        setId: (ChatMessageEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ChatMessageEntity object, fb.Builder fbb) {
          final sessionIdOffset = fbb.writeString(object.sessionId);
          final articleIdOffset = fbb.writeString(object.articleId);
          final roleOffset = fbb.writeString(object.role);
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, sessionIdOffset);
          fbb.addOffset(2, articleIdOffset);
          fbb.addOffset(3, roleOffset);
          fbb.addOffset(4, contentOffset);
          fbb.addInt64(5, object.createdAt);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final sessionIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final articleIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final roleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final createdAtParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = ChatMessageEntity(
              id: idParam,
              sessionId: sessionIdParam,
              articleId: articleIdParam,
              role: roleParam,
              content: contentParam,
              createdAt: createdAtParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ArticleEmbedding] entity fields to define ObjectBox queries.
class ArticleEmbedding_ {
  /// See [ArticleEmbedding.id].
  static final id =
      obx.QueryIntegerProperty<ArticleEmbedding>(_entities[0].properties[0]);

  /// See [ArticleEmbedding.articleId].
  static final articleId =
      obx.QueryStringProperty<ArticleEmbedding>(_entities[0].properties[1]);

  /// See [ArticleEmbedding.content].
  static final content =
      obx.QueryStringProperty<ArticleEmbedding>(_entities[0].properties[2]);

  /// See [ArticleEmbedding.embedding].
  static final embedding =
      obx.QueryHnswProperty<ArticleEmbedding>(_entities[0].properties[3]);
}

/// [ChatMessageEntity] entity fields to define ObjectBox queries.
class ChatMessageEntity_ {
  /// See [ChatMessageEntity.id].
  static final id =
      obx.QueryIntegerProperty<ChatMessageEntity>(_entities[1].properties[0]);

  /// See [ChatMessageEntity.sessionId].
  static final sessionId =
      obx.QueryStringProperty<ChatMessageEntity>(_entities[1].properties[1]);

  /// See [ChatMessageEntity.articleId].
  static final articleId =
      obx.QueryStringProperty<ChatMessageEntity>(_entities[1].properties[2]);

  /// See [ChatMessageEntity.role].
  static final role =
      obx.QueryStringProperty<ChatMessageEntity>(_entities[1].properties[3]);

  /// See [ChatMessageEntity.content].
  static final content =
      obx.QueryStringProperty<ChatMessageEntity>(_entities[1].properties[4]);

  /// See [ChatMessageEntity.createdAt].
  static final createdAt =
      obx.QueryIntegerProperty<ChatMessageEntity>(_entities[1].properties[5]);
}
